-- MySQL Script generated by MySQL Workbench
-- mié 14 abr 2021 18:28:38 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bykfnabpbn8vqi39xlct
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bykfnabpbn8vqi39xlct
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bykfnabpbn8vqi39xlct` ;
USE `bykfnabpbn8vqi39xlct` ;

-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Suppliers` (
  `SupplierID` INT NOT NULL,
  `CompanyName` NVARCHAR(40) NULL,
  `ContactName` NVARCHAR(30) NULL,
  `ContactTitle` NVARCHAR(30) NULL,
  `Address` NVARCHAR(60) NULL,
  `City` NVARCHAR(15) NULL,
  `Region` NVARCHAR(15) NULL,
  `PostalCode` NVARCHAR(10) NULL,
  `Country` NVARCHAR(15) NULL,
  `Phone` NVARCHAR(24) NULL,
  `Fax` NVARCHAR(24) NULL,
  `HomePage` LONGTEXT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Categories` (
  `CategoryID` INT NOT NULL,
  `CategoryName` NVARCHAR(15) NULL,
  `Description` LONGTEXT NULL,
  `Picture` BLOB NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Products` (
  `ProductID` INT NOT NULL,
  `ProductName` NVARCHAR(40) NULL,
  `SupplierID` INT NULL,
  `CategoryID` INT NOT NULL,
  `QuantityPerUnit` NVARCHAR(20) NULL,
  `UnitPrice` DECIMAL(15,4) NULL,
  `UnitsInStock` SMALLINT NULL,
  `UnitsOnOrder` SMALLINT NULL,
  `ReorderLevel` SMALLINT NULL,
  `Discontinued` TINYINT NULL,
  PRIMARY KEY (`ProductID`, `CategoryID`),
  INDEX `fk_Products_Categories1_idx` (`CategoryID` ASC) VISIBLE,
  INDEX `fk_Products_Suppliers1_idx` (`SupplierID` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Categories1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Categories` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Suppliers1`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Suppliers` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Employees` (
  `EmployeeID` INT NOT NULL,
  `LastName` NVARCHAR(20) NULL,
  `FirstName` NVARCHAR(10) NULL,
  `Title` NVARCHAR(30) NULL,
  `TitleOfCourtesy` NVARCHAR(25) NULL,
  `BirthDate` DATETIME(3) NULL,
  `HireDate` DATETIME(3) NULL,
  `Address` NVARCHAR(60) NULL,
  `City` NVARCHAR(15) NULL,
  `Region` NVARCHAR(15) NULL,
  `PostalCode` NVARCHAR(10) NULL,
  `Country` NVARCHAR(15) NULL,
  `HomePhone` NVARCHAR(24) NULL,
  `Extension` NVARCHAR(4) NULL,
  `Photo` LONGBLOB NULL,
  `Notes` LONGTEXT NULL,
  `ReportsTo` INT NULL,
  `PhotoPath` NVARCHAR(255) NULL,
  PRIMARY KEY (`EmployeeID`),
  INDEX `fk_Employees_Employees1_idx` (`ReportsTo` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Employees1`
    FOREIGN KEY (`ReportsTo`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Shippers` (
  `ShipperID` INT NOT NULL,
  `CompanyName` NVARCHAR(40) NULL,
  `Phone` NVARCHAR(24) NULL,
  PRIMARY KEY (`ShipperID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Customers` (
  `CustomerID` NCHAR(5) NOT NULL,
  `CompanyName` NVARCHAR(40) NULL,
  `ContactName` NVARCHAR(30) NULL,
  `ContactTitle` NVARCHAR(30) NULL,
  `Address` NVARCHAR(60) NULL,
  `City` NVARCHAR(15) NULL,
  `Region` NVARCHAR(15) NULL,
  `PostalCode` NVARCHAR(10) NULL,
  `Country` NVARCHAR(15) NULL,
  `Phone` NVARCHAR(24) NULL,
  `Fax` NVARCHAR(24) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Orders` (
  `OrderID` INT NOT NULL,
  `CustomerID` NCHAR(5) NOT NULL,
  `EmployeeID` INT NOT NULL,
  `OrderDate` DATETIME(3) NULL,
  `RequiredDate` DATETIME(3) NULL,
  `ShippedDate` DATETIME(3) NULL,
  `ShipVia` INT NOT NULL,
  `Freight` DECIMAL(15,4) NULL,
  `ShipName` NVARCHAR(40) NULL,
  `ShipAddress` NVARCHAR(60) NULL,
  `ShipCity` NVARCHAR(15) NULL,
  `ShipRegion` NVARCHAR(15) NULL,
  `ShipPostalCode` NVARCHAR(10) NULL,
  `ShipCountry` NVARCHAR(15) NULL,
  PRIMARY KEY (`OrderID`, `CustomerID`, `EmployeeID`, `ShipVia`),
  INDEX `fk_Orders_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  INDEX `fk_Orders_Shippers1_idx` (`ShipVia` ASC) VISIBLE,
  INDEX `fk_Orders_Customers1_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Shippers1`
    FOREIGN KEY (`ShipVia`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Shippers` (`ShipperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`OrderDetails` (
  `OrderID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `UnitPrice` DECIMAL(15,4) NULL,
  `Quantity` SMALLINT NULL,
  `Discount` REAL NULL,
  PRIMARY KEY (`OrderID`, `ProductID`),
  INDEX `fk_OrderDetails_Products1_idx` (`ProductID` ASC) VISIBLE,
  INDEX `fk_OrderDetails_Orders1_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetails_Products1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetails_Orders1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Region` (
  `RegionID` INT NOT NULL,
  `RegionDescription` NCHAR(50) NULL,
  PRIMARY KEY (`RegionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`Territories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`Territories` (
  `TerritoryID` NVARCHAR(20) NOT NULL,
  `TerritoryDescription` NCHAR(50) NULL,
  `RegionID` INT NOT NULL,
  PRIMARY KEY (`TerritoryID`, `RegionID`),
  INDEX `fk_Territories_Region1_idx` (`RegionID` ASC) VISIBLE,
  CONSTRAINT `fk_Territories_Region1`
    FOREIGN KEY (`RegionID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Region` (`RegionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`EmployeeTerritories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`EmployeeTerritories` (
  `EmployeeID` INT NOT NULL,
  `TerritoryID` NVARCHAR(20) NOT NULL,
  PRIMARY KEY (`EmployeeID`, `TerritoryID`),
  INDEX `fk_EmployeeTerritories_Employees1_idx` (`EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_EmployeeTerritories_Territories1`
    FOREIGN KEY (`TerritoryID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Territories` (`TerritoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EmployeeTerritories_Employees1`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`CustomerDemographics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`CustomerDemographics` (
  `CustomerTypeID` NCHAR(10) NOT NULL,
  `CustomerDesc` LONGTEXT NULL,
  PRIMARY KEY (`CustomerTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bykfnabpbn8vqi39xlct`.`CustomerCustomerDemo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bykfnabpbn8vqi39xlct`.`CustomerCustomerDemo` (
  `CustomerID` NCHAR(5) NOT NULL,
  `CustomerTypeID` NCHAR(10) NOT NULL,
  PRIMARY KEY (`CustomerID`, `CustomerTypeID`),
  INDEX `fk_CustomersCustomersDemo_CustomersDemographics1_idx` (`CustomerTypeID` ASC) VISIBLE,
  INDEX `fk_CustomersCustomersDemo_Customers1_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_CustomersCustomersDemo_CustomersDemographics1`
    FOREIGN KEY (`CustomerTypeID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`CustomerDemographics` (`CustomerTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomersCustomersDemo_Customers1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `bykfnabpbn8vqi39xlct`.`Customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
